// angular/src/app/components/add-task/add-task.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { Subscription } from 'rxjs';
import { ITask } from 'src/app/interfaces/ITask';
import { UiService } from 'src/app/services/ui.service';

@Component({
  selector: 'app-add-task',
  templateUrl: './add-task.component.html',
  styleUrls: ['./add-task.component.scss']
})
export class AddTaskComponent {
  @Output() public onAddTask: EventEmitter<ITask> = new EventEmitter();
  public text: string = "";
  public day: string = "";
  public reminder: boolean = false;
  public showAddTask: boolean = false;
  public subscription: Subscription = Subscription.EMPTY;

  constructor(protected uiService: UiService){
    this.subscription = this.uiService
      .onToggle()
      .subscribe((value)=>(this.showAddTask=value));
  }

  ngOnInit(): void{

  }

  public onSubmit(): void{
    if(!this.text){
      alert('Please add a task!');
      
      return;
    }

    const newTask: ITask = {
      text: this.text,
      day: this.day,
      reminder: this.reminder
    }

    this.onAddTask.emit(newTask);

    this.text='';
    this.day='';
    this.reminder=false;

  }

}

<form *ngIf="showAddTask" 
       class="add-form"
      (ngSubmit)="onSubmit()">
    <div class="form-control">
        <label for="text">Task</label>
        <input type="text" 
               name="text" 
               [(ngModel)]="text" 
               id="text" 
               placeholder="Add Task">
    </div>
    <div class="form-control">
        <label for="day">Day & Time</label>
        <input type="text" 
               name="day"
               [(ngModel)]="day" 
               id="day" 
               placeholder="Add Day & Time">
    </div>
    <div class="form-control-check">
        <label for="reminder">Set Reminder</label>
        <input type="checkbox" 
               name="reminder"
               [(ngModel)]="reminder"
               id="reminder">
    </div>
    <input type="submit" 
           value="Save Task" 
           class="btn">
    <!-- <app-button color="accent" text="Save Task"></app-button> -->
    
</form>

// react/src/components/AddTask.tsx
import React, { useState } from "react";
import { ITask } from "../interfaces/ITask";

// interface IProps {
//   onAdd: (addProps: IAddProps) => void;
// }
interface IProps {
  onAdd: (addProps: ITask) => void;
}

const AddTask = ({ onAdd }: IProps) => {
  const [text, setText] = useState("");
  const [day, setDay] = useState("");
  const [reminder, setReminder] = useState(false);

  const onSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    if (!text) {
      alert("Please add a task");
      return;
    }

    onAdd({ text, day, reminder });

    setText("");
    setDay("");
    setReminder(false);
  };

  return (
    <form className="add-form" onSubmit={onSubmit}>
      <div className="form-control">
        <label>Task</label>
        <input
          type="text"
          placeholder="Add task"
          value={text}
          onChange={(e) => setText(e.target.value)}
        />
      </div>
      <div className="form-control">
        <label>Day & Time</label>
        <input
          type="text"
          placeholder="Add day & time"
          value={day}
          onChange={(e) => setDay(e.target.value)}
        />
      </div>
      <div className="form-control form-control-check">
        <label>Set reminder</label>
        <input
          type="checkbox"
          checked={reminder}
          onChange={(e) => setReminder(e.currentTarget.checked)}
        />
      </div>

      <input type="submit" value="Save task" className="btn btn-block" />
    </form>
  );
};

export default AddTask;
